In [1]:
import numpy as np

NumPy의 배열 = ndarray 클래스 : 데이터가 같은 자료형

In [2]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [3]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [4]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

* b	불리언	b (참 혹은 거짓)
* i	정수	i8 (64비트)
* u	부호 없는 정수	u8 (64비트)
* f	부동소수점	f8 (64비트)
* c	복소 부동소수점	c16 (128비트)
* O	객체	0 (객체에 대한 포인터)
* S	바이트 문자열	S24 (24 글자)
* U	유니코드 문자열	U24 (24 유니코드 글자)

In [5]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [6]:
x[0] + x[1]

3.0

In [7]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [8]:
x[0] + x[1]

'12'

# Inf & NaN

In [9]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\TAEHYEONG\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\TAEHYEONG\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [10]:
np.log(0)

C:\Users\TAEHYEONG\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [11]:
np.exp(-np.inf)

0.0

## 배열 생성

* zeros : 크기가 정해져 있고 모든 값이 0인 배열

In [12]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [13]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
c = np.zeros((5, 2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [15]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [16]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

* ones : 1로 초기화된 배열 생성

In [17]:
e = np.ones((2, 3, 4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

* ones_like, zeros_like : 다른 배열과 같은 크기의 배열 생성

In [18]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

* empty : 특정한 값으로 초기화를 하지 않음, 메모리 값

In [19]:
g = np.empty((4, 3))
g

array([[1.24611816e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.75983079e+164],
       [7.78696294e-091, 4.18201642e-062, 2.82998827e-033],
       [6.45084254e-067, 6.48224659e+170, 4.93432906e+257]])

* arange : 특정한 규칙에 따라 증가하는 수열 생성(=range)

In [20]:
np.arange(10)  # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

* linspace, logspace : 선형 또는 로그 구간을 지정한 구간의 수만큼 분할

In [22]:
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

# 전치(transpose) 연산

In [24]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# 배열의 크기 변형

In [26]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체 가능

In [28]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [30]:
a.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

* flatten, ravel : 다차원 배열을 1차원으로 펼치기

In [31]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [34]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [35]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

* newaxis : 차원만 1차원 증가시키는 경우

In [36]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# 배열 연결

In [37]:
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [39]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [40]:
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* dstack : 깊이(depth) 방향으로 배열을 합침

In [43]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [46]:
(np.dstack([c1, c2])).shape

(3, 4, 2)

* stack

In [47]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [48]:
c.shape

(2, 3, 4)

In [49]:
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [50]:
c.shape

(3, 2, 4)

* 인덱서(indexer) : 특수 메서드

In [51]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [52]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

* tile : 동일한 배열을 반복하여 연결

In [53]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [54]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])