# 벡터화 연산

* %%time : 셀 코드의 실행시간을 측정하는 IPython 매직 명령

In [1]:
import numpy as np

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [3]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 15 ms


In [4]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [5]:
%%time
z = x + y

Wall time: 991 µs


In [6]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

벡터화 연산의 속도가 더 빠름

In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [8]:
a == b

array([False,  True, False,  True])

In [9]:
a >= b

array([False,  True,  True,  True])

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [11]:
np.all(a == b)

False

In [12]:
np.all(a == c)

True

In [13]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [14]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [16]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

# 스칼라와 벡터/행렬의 곱셈

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [19]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

# 브로드캐스팅

In [21]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [22]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [23]:
x + y

array([1, 2, 3, 4, 5])

In [24]:
x + 1

array([1, 2, 3, 4, 5])

In [25]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [26]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [27]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [28]:
y = np.arange(3)
y

array([0, 1, 2])

In [29]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])