* 배열(array)
    1. 모든 원소가 같은 자료형이어야 한다.
    2. 원소의 갯수를 바꿀 수 없다.

In [1]:
import numpy as np

## 1차원 배열

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

배열과 리스트 차이점 : 배열은 연속적인 메모리 배치로 모든 원소가 같은 자료형을 가짐, 때문에 원소에 대한 접근과 반복문 실행이 빠름

### 벡터화 연산(vectorized operation)

In [4]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
answer = []
for di in data:
    answer.append(2*di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [10]:
2 * a + b

array([12, 24, 36])

In [11]:
a == 2

array([False,  True, False])

In [12]:
b > 10

array([False,  True,  True])

In [13]:
(a == 2) & (b > 10)

array([False,  True, False])

## 2차원 배열

In [14]:
c = np.array([[0, 1, 2], [3, 4, 5]]) # 2 × 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
len(c) # 행의 갯수

2

In [16]:
len(c[0]) # 열의 갯수

3

## 3차원 배열

In [17]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [18]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

# 배열의 차원과 크기

* ndim : 배열의 차원
* shape : 배열의 크기

In [19]:
# a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [20]:
# c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [21]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


# 배열의 인덱싱

In [22]:
a = np.array([0, 1, 2, 3, 4])

In [23]:
a[2]

2

In [24]:
a[-1]

4

In [25]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

* 다차원 배열일 때는 다음과 같이 콤마(comma ,)를 사용하여 접근

In [26]:
a[0, 0]  # 첫번째 행의 첫번째 열

0

In [27]:
a[0, 1]  # 첫번째 행의 두번째 열

1

In [28]:
a[-1, -1]  # 마지막 행의 마지막 열

5

# 배열 슬라이싱

In [29]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [30]:
a[0, :]  # 첫번째 행 전체

array([0, 1, 2, 3])

In [31]:
a[:, 1]  # 두번째 열 전체

array([1, 5])

In [32]:
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [33]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

# 팬시 인덱싱(fancy indexing)

In [34]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [35]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [36]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [37]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [38]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [39]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [42]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])